### PR TITLE
Jb54282

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Comment by martyone** [comment]
Just the very last commit belongs to this PR

**Comment by martyone** [comment]
https://codereview.qt-project.org/c/qt-creator/qt-creator/+/349540

**Review by vigejolla — APPROVED** [review]
This is used only for displaying paths? The discussion on upstream review was interesting. I'm slightly worried about what happens when someone has a path which actually has a backslash in the name. But if it's good enough for upstream it's good enough for me. And it's nice to know that the "real" fix, i.e. pathnames already knowing which separators they use, is already cooking in upstream.

**Comment by martyone** [comment]
Nope, it's not only for displaying. It modifies the real data.

**Pull request merged**
