### PR TITLE
A few improvements for merssh

### PR DESCRIPTION
**Pull request by Kaffeine**
I think that I did it right, but please, check that cb5562e is correct before merge :)

### CODE REVIEW

**Comment by Kaffeine** [comment]
>Parent class' default constructor is called implicitly AFAIK
You're right, so I removed the commit.

**Comment by Kaffeine** [comment]
Hello @martyone,

does it look good to you now or there is something to fix?

**Comment by martyone** [comment]
@Kaffeine Except that I am not sure about linking Core plugin here it LGTM. I am going to merge it only after the upgrade to 4.2 is merged anyway.

**Comment by Kaffeine** [comment]
>I am not sure about linking Core plugin here

what is the difference from any of
[merabstractvmstartstep.cpp](https://github.com/sailfish-sdk/sailfish-qtcreator/blob/master/src/plugins/mer/merabstractvmstartstep.cpp#L32)
[merconnection](https://github.com/sailfish-sdk/sailfish-qtcreator/blob/master/src/plugins/mer/merconnection.cpp#L29)
[merdeploysteps](https://github.com/sailfish-sdk/sailfish-qtcreator/blob/master/src/plugins/mer/merdeploysteps.cpp#L42)
[merdevicefactory](https://github.com/sailfish-sdk/sailfish-qtcreator/blob/master/src/plugins/mer/merdevicefactory.cpp#L33)

and a dozen other files in the mer plugin with the exactly same include?

**Comment by martyone** [comment]
Only now I noticed this is a change in Mer plugin - your commit says "A few improvements for merssh" :) So using ICore is OK there but I would like to ask you to split it out into a separate commit.

**Comment by Kaffeine** [comment]
>your commit says "A few improvements for merssh" :) 

There is no such commit. It is a PR with improvements for (not *in*) merssh. The first one is [Mer: Move merssh to libexec](https://github.com/sailfish-sdk/sailfish-qtcreator/pull/101/commits/bb03ebe5e26b171c97832f54e475578dab31aade) and the second is [merssh: Cleanup includes](https://github.com/sailfish-sdk/sailfish-qtcreator/pull/101/commits/056389417193d03c61879cc850de62beaf243a5f)

>I would like to ask you to split it out into a separate commit.

Let's clarify: do you want me to split the move commit ? But it's an atomic commit in terms that if I move the tool then I need to adjust references, we'll have an incoherent state otherwise.

**Comment by martyone** [comment]
@Kaffeine You are absolutely right! I am sorry, being in a hurry I missed that the PR consists of two commits. LGTM. (stupid github interface with its preference to review a PR as whole instead of separate commits). Have a nice weekend!

**Comment by Kaffeine** [comment]
Thanks!

**Comment by Kaffeine** [comment]
I can not find the commits in any branch. Did you cherry-picked them or is this PR completely dropped (what is the reason for close)?

**Comment by martyone** [comment]
@Kaffeine that was just how github deals with removed destination branch - if it at least didn't say it was me who closed it :) I will reopen it and change the destinaton to master as the 4.2 work from 'next' has been already merged. Thanks for asking. I plan to include it in the next-next SDK release (before end of this year possibly) - timing for the immediate-next release is tight.

**Comment by Kaffeine** [comment]
> martyone closed this 4 hours ago

Actually, github says that :-) Thank you for reopen. I'm looking forward to get back to QtC and SDK sometime soon, probably at late November.

**Comment by martyone** [comment]
@Kaffeine please rebase on top of master

**Comment by Kaffeine** [comment]
@martyone: done

**Pull request merged**
