### PR TITLE
Jb55462

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Comment by martyone** [comment]
Just the last two commits belong to this PR

**Review by vigejolla — APPROVED** [review]
LGTM, with a small caveat: I didn't try how this actually feels, as I didn't have a recent enough build of QtC and building takes ages. It's building now so I'll test when it's done.

**Comment by martyone** [comment]
Polished once more. Now it delays displaying the progress dialog when there is no pop up dialog open - the assumption is that in this case the action was triggered using the buttons in bottom left corner and those already provide necessary feedback. The progress bar will only show if it takes too long - like before. Also fixed stacking the progress bar on top of other windows when a pop up dialog is open (e.g. when starting/stopping the VM from options dialog).

**Comment by vigejolla** [comment]
tested now, both before and after polishing. My "lgtm" still stands :)

**Pull request merged**
