### PR TITLE
Jb54737

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Comment by martyone** [comment]
Just the very last commit belongs to this PR.

**Review by vigejolla — APPROVED** [review]
LGTM

**Review by vigejolla — COMMENTED** [review]
... when EA and latest are of the same version. LGTM.

**Comment by martyone** [comment]
Here I really meant latest non-EA, but later, when working on alignment of the listing with and without --available, I found it better to keep the same order and list EA first (later PR does it)

**Pull request merged**
